# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kate/Programming/QC/qc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kate/Programming/QC/qc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kate/Programming/QC/qc/CMakeFiles /home/kate/Programming/QC/qc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kate/Programming/QC/qc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qc

# Build rule for target.
qc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qc
.PHONY : qc

# fast build rule for target.
qc/fast:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/build
.PHONY : qc/fast

src/genomeseq.o: src/genomeseq.cpp.o
.PHONY : src/genomeseq.o

# target to build an object file
src/genomeseq.cpp.o:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/genomeseq.cpp.o
.PHONY : src/genomeseq.cpp.o

src/genomeseq.i: src/genomeseq.cpp.i
.PHONY : src/genomeseq.i

# target to preprocess a source file
src/genomeseq.cpp.i:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/genomeseq.cpp.i
.PHONY : src/genomeseq.cpp.i

src/genomeseq.s: src/genomeseq.cpp.s
.PHONY : src/genomeseq.s

# target to generate assembly for a file
src/genomeseq.cpp.s:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/genomeseq.cpp.s
.PHONY : src/genomeseq.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/seqparser.o: src/seqparser.cpp.o
.PHONY : src/seqparser.o

# target to build an object file
src/seqparser.cpp.o:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/seqparser.cpp.o
.PHONY : src/seqparser.cpp.o

src/seqparser.i: src/seqparser.cpp.i
.PHONY : src/seqparser.i

# target to preprocess a source file
src/seqparser.cpp.i:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/seqparser.cpp.i
.PHONY : src/seqparser.cpp.i

src/seqparser.s: src/seqparser.cpp.s
.PHONY : src/seqparser.s

# target to generate assembly for a file
src/seqparser.cpp.s:
	$(MAKE) -f CMakeFiles/qc.dir/build.make CMakeFiles/qc.dir/src/seqparser.cpp.s
.PHONY : src/seqparser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... qc"
	@echo "... rebuild_cache"
	@echo "... src/genomeseq.o"
	@echo "... src/genomeseq.i"
	@echo "... src/genomeseq.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/seqparser.o"
	@echo "... src/seqparser.i"
	@echo "... src/seqparser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

